---
title: "ML-04-AlGhammari-Schmidt"
author: "Bernd Schmidt , Osamah Al-Ghammari"
date: "November 03, 2017"
output: pdf_document
---

```{r setup, message=FALSE, results='hide'}
require(corrplot)
require(plyr)
require(png)
require(caret)
library(doMC)
registerDoMC(3)
```

```{r read_images}
# filedir
filedir <- "../dat/dsr-preprocessed-1000x1333_faces_haar_gray_resized150_equalized_50x50"
# get all filenames
filenames <- list.files(filedir, full.names = T, pattern="*.png")
# filter filename for each person
faces <- ldply(strsplit(filenames, split="_"))[,8:9]
# rename columns for better understanding
names(faces) <- c("pers", "pic")
faces$pers <- as.numeric(faces$pers)
#faces$path <- filenames

# load face data to data structure
faces$data <- ldply(filenames, function(f) (t(as.numeric(readPNG(f)))))
faces_data <- faces$data
```

```{r feature_correlation}
# feature correlation as plot
#corrplot(cor(faces_data), 'circle') # addgrid.col = NA
corrplot(cor(faces$data), tl.cex = 0.3) # addgrid.col = NA
# remove correlated variable using ?findCorrelation
foundCorIndexes <- findCorrelation(cor(faces$data))
foundCorIndexes
corrplot(cor(faces$data[,-foundCorIndexes]), tl.cex = 0.3)

faces$data <- faces$data[,-foundCorIndexes]
```

```{r data_partitioning}
# split into training and test data
set.seed(1704)
indexes_train <- createDataPartition(faces$pers, p=0.75, list = F)
indexes_test <- (1:nrow(faces$data))[-indexes_train]

training <- faces[indexes_train,]
testing <- faces[indexes_test,]
```

```{r feature_selection}
sbfRes <- sbf(x = training$data, y = training$pers, sbfControl = sbfControl(functions = rfSBF, method = 'repeatedcv', repeats = 5)) # more repeats are better
sbfRes
sbfRes$optVariables # all 10 features
faces$data <- faces$data[,sbfRes$optVariables]
```

```{r model_training}
model <- train(training$data,
               factor(training$pers),
               method = 'knn',
               preProcess = c('center', 'scale', 'pca'),
               metric = 'Kappa',
               trControl = trainControl(
                 method = 'LOOCV',
                 preProcOptions = list(thresh = 0.7)
               )
               )
model
varImp(model)
```

```{r predict_test_data}
predicted <- predict(model, newdata = testing$data)

conf <- confusionMatrix(predicted, factor(testing$pers))

```