---
title: "ML-05-AlGhammari-Schmidt"
author: "Bernd Schmidt , Osamah Al-Ghammari"
date: "November 03, 2017"
output: pdf_document
---

```{r setup, message=FALSE, results='hide'}
require(plyr)
require(lattice)
require(ggplot2)
require(kernlab)
require(caret)
require(doMC)
library(pROC)
registerDoMC(3)
library(zoo)
```

# Gesture Recognition

```{r read data}
filedir <- "../dat"
  
# get all filenames
filenames <- list.files(filedir, full.names = T, pattern="*.csv")

gestures <- ldply(filenames, read.table, sep=',', fill = T, col.names = c('gesture', 'person', 'sample', paste('acc', 1:1000, sep='')))

```

## Visualization

Currently the samples have different lengths and there are **NA** at the start and/or the end of the sample.

```{r visualize}
matplot(t(gestures[1:10,4:1003]), type='l', col=factor(gestures[1:10,1]))
```

## Optimization
For optimization, all **NA** values are removed and the values are interpolated to 1000 values per sample.
After that, a rolling median is applied to the sample to smooth it.

```{r optimize}
stepwidth <- 1/1000
gestures_opt <- as.data.frame(t(apply(gestures, 1, function(r) {
  row <- r[!is.na(r)] # remove all NA values
  row_approx <- approx(x = seq(0,1,1/(length(row[4:length(row)])-1)), y = row[4:length(row)], xout = seq(0,1,stepwidth), method = 'linear')$y # interpolate
  #row_runmed <- as.numeric(runmed(row_approx, k = 11)) # filter
  rollapply(row_approx, 11, median, na.rm=T)
  r[4:1003] <- row_approx[1:1000] # store calcuated values back to row with meta info
  r
})
))
matplot(t(gestures_opt[1:10,4:1003]), type='l', col=factor(gestures_opt[1:10,1]))
```